spring.application.name=auth-service
server.port=4005

spring.datasource.url=jdbc:postgresql://localhost:5432/DauthDB
spring.datasource.username=postgres
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=YWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWFhYWE=
