spring.application.name=auth-service
server.port=4005

spring.datasource.url=jdbc:postgresql://auth-db.c41uusgs8d4c.us-east-1.rds.amazonaws.com:5432/authdb
spring.datasource.username=postgres
spring.datasource.password=password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret=hYWFhSulabhAmbulePCBAFTER6monthsFromNowWFhYWFhYWE=
