### Post request to create an example patient Entity
POST http://localhost:4000/patients
Content-Type: application/json

{
  "name" : "Sulabh Ambule",
  "email" : "sulabh1234@gmail.com",
  "address" : "Gondia, Maharashtra",
  "dateOfBirth" : "2005-09-22",
  "registeredDate" : "2025-20-06"
}
###