### Put request to update existing patient
PUT http://localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name" : "UPDATED",
  "email" : "UPDATED@example.com",
  "address" : "Address",
  "dateOfBirth" : "2005-06-28"

}
###