### Login Request to retrieve a token
POST http://localhost:4004/auth/login
Content-Type: application/json

{
  "email":"admin@gmail.com",
  "password":"admin123"
}

> {% client.global.set("token", response.body.token) %}