spring.datasource.url=jdbc:postgresql://patient-db.c41uusgs8d4c.us-east-1.rds.amazonaws.com:5432/patientdb
:5432/patientdb
spring.datasource.username=postgres
spring.datasource.password=password


server.port=4000
billing.service.address=billing-service
billing.service.grpc.port=9001

spring.kafka.bootstrap-servers=kafka:9092