spring.application.name=patient-service

server.port=4000

spring.datasource.url=jdbc:postgresql://localhost:5432/Dpatientdb
spring.datasource.username=postgres
spring.datasource.password=root123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

billing.service.address=localhost
billing.service.grpc.port=9001
