spring.datasource.url=jdbc:postgresql://patient-service-db:5432/patientdb
spring.datasource.username=postgres
spring.datasource.password=root123


server.port=4000
billing.service.address=billing-service
billing.service.grpc.port=9001

spring.kafka.bootstrap-servers=kafka:9092